# -*- coding: utf-8 -*-
"""
Created on 15:51, 19/11/15
CSV cannot recognize dic{{}}, this module is discarded, using mongochef to export
@author: wt
"""

import db_util as dbutil
import csv

def export_poi(dbname, colname, file_name):
    db = dbutil.db_connect_no_auth(dbname)
    poidb = db[colname]
    cursor = poidb.find({"timeline_count": {'$gte': 3000}}, {'_id': 0,
                                                             'id': 1,
                                                             "screen_name": 1,
                                                             'created_at': 1,
                                                             'description': 1,
                                                             'timeline_count': 1,
                                                             'lang': 1,
                                                             'location': 1,
                                                             'ds_gender': 1,
                                                             'text_anal.gw.value': 1,
                                                             'text_anal.cw.value': 1,
                                                             'text_anal.edword_count.value': 1,
                                                             'text_anal.h.value': 1,
                                                             'text_anal.a.value': 1,
                                                             'text_anal.lw.value': 1,
                                                             'text_anal.hw.value': 1,
                                                             'rliwc_anal.result.WC': 1,
                                                             'liwc_anal.result.WPS': 1,
                                                             'liwc_anal.result.Sixltr': 1,
                                                             'liwc_anal.result.Dic': 1,
                                                             'liwc_anal.result.Numerals': 1,
                                                             'liwc_anal.result.funct': 1,
                                                             'liwc_anal.result.pronoun': 1,
                                                             'liwc_anal.result.ppron': 1,
                                                             'liwc_anal.result.i': 1,
                                                             'liwc_anal.result.we': 1,
                                                             'liwc_anal.result.you': 1,
                                                             'liwc_anal.result.shehe': 1,
                                                             'liwc_anal.result.they': 1,
                                                             'liwc_anal.result.ipron': 1,
                                                             'liwc_anal.result.article': 1,
                                                             'liwc_anal.result.verb': 1,
                                                             'liwc_anal.result.auxverb': 1,
                                                             'liwc_anal.result.past': 1,
                                                             'liwc_anal.result.present': 1,
                                                             'liwc_anal.result.future': 1,
                                                             'liwc_anal.result.adverb': 1,
                                                             'liwc_anal.result.preps': 1,
                                                             'liwc_anal.result.conj': 1,
                                                             'liwc_anal.result.negate': 1,
                                                             'liwc_anal.result.quant': 1,
                                                             'liwc_anal.result.number': 1,
                                                             'liwc_anal.result.swear': 1,
                                                             'liwc_anal.result.social': 1,
                                                             'liwc_anal.result.family': 1,
                                                             'liwc_anal.result.friend': 1,
                                                             'liwc_anal.result.humans': 1,
                                                             'liwc_anal.result.affect': 1,
                                                             'liwc_anal.result.posemo': 1,
                                                             'liwc_anal.result.negemo': 1,
                                                             'liwc_anal.result.anx': 1,
                                                             'liwc_anal.result.anger': 1,
                                                             'liwc_anal.result.sad': 1,
                                                             'liwc_anal.result.cogmech': 1,
                                                             'liwc_anal.result.insight': 1,
                                                             'liwc_anal.result.cause': 1,
                                                             'liwc_anal.result.discrep': 1,
                                                             'liwc_anal.result.tentat': 1,
                                                             'liwc_anal.result.certain': 1,
                                                             'liwc_anal.result.inhib': 1,
                                                             'liwc_anal.result.incl': 1,
                                                             'liwc_anal.result.excl': 1,
                                                             'liwc_anal.result.percept': 1,
                                                             'liwc_anal.result.see': 1,
                                                             'liwc_anal.result.hear': 1,
                                                             'liwc_anal.result.feel': 1,
                                                             'liwc_anal.result.bio': 1,
                                                             'liwc_anal.result.body': 1,
                                                             'liwc_anal.result.health': 1,
                                                             'liwc_anal.result.sexual': 1,
                                                             'liwc_anal.result.ingest': 1,
                                                             'liwc_anal.result.relativ': 1,
                                                             'liwc_anal.result.motion': 1,
                                                             'liwc_anal.result.space': 1,
                                                             'liwc_anal.result.time': 1,
                                                             'liwc_anal.result.work': 1,
                                                             'liwc_anal.result.achieve': 1,
                                                             'liwc_anal.result.leisure': 1,
                                                             'liwc_anal.result.home': 1,
                                                             'liwc_anal.result.money': 1,
                                                             'liwc_anal.result.relig': 1,
                                                             'liwc_anal.result.death': 1,
                                                             'liwc_anal.result.assent': 1,
                                                             'liwc_anal.result.nonfl': 1,
                                                             'liwc_anal.result.filler': 1,
                                                             'liwc_anal.result.Period': 1,
                                                             'liwc_anal.result.Comma': 1,
                                                             'liwc_anal.result.Colon': 1,
                                                             'liwc_anal.result.SemiC': 1,
                                                             'liwc_anal.result.QMark': 1,
                                                             'liwc_anal.result.Exclam': 1,
                                                             'liwc_anal.result.Dash': 1,
                                                             'liwc_anal.result.Quote': 1,
                                                             'liwc_anal.result.Apostro': 1,
                                                             'liwc_anal.result.Parenth': 1,
                                                             'liwc_anal.result.OtherP': 1,
                                                             'liwc_anal.result.AllPct': 1
                                                             })
    with open(file_name+'.csv', 'w') as outfile:
        fields = ['id',
                  "screen_name",
                  'created_at',
                  'description',
                  'timeline_count',
                  'lang',
                  'location',
                  'ds_gender',
                  'text_anal.gw.value',
                  'text_anal.cw.value',
                  'text_anal.edword_count.value',
                  'text_anal.h.value',
                  'text_anal.a.value',
                  'text_anal.lw.value',
                  'text_anal.hw.value',
                  'liwc_anal.result.WC',
                  'liwc_anal.result.WPS',
                  'liwc_anal.result.Sixltr',
                  'liwc_anal.result.Dic',
                  'liwc_anal.result.Numerals',
                  'liwc_anal.result.funct',
                  'liwc_anal.result.pronoun',
                  'liwc_anal.result.ppron',
                  'liwc_anal.result.i',
                  'liwc_anal.result.we',
                  'liwc_anal.result.you',
                  'liwc_anal.result.shehe',
                  'liwc_anal.result.they',
                  'liwc_anal.result.ipron',
                  'liwc_anal.result.article',
                  'liwc_anal.result.verb',
                  'liwc_anal.result.auxverb',
                  'liwc_anal.result.past',
                  'liwc_anal.result.present',
                  'liwc_anal.result.future',
                  'liwc_anal.result.adverb',
                  'liwc_anal.result.preps',
                  'liwc_anal.result.conj',
                  'liwc_anal.result.negate',
                  'liwc_anal.result.quant',
                  'liwc_anal.result.number',
                  'liwc_anal.result.swear',
                  'liwc_anal.result.social',
                  'liwc_anal.result.family',
                  'liwc_anal.result.friend',
                  'liwc_anal.result.humans',
                  'liwc_anal.result.affect',
                  'liwc_anal.result.posemo',
                  'liwc_anal.result.negemo',
                  'liwc_anal.result.anx',
                  'liwc_anal.result.anger',
                  'liwc_anal.result.sad',
                  'liwc_anal.result.cogmech',
                  'liwc_anal.result.insight',
                  'liwc_anal.result.cause',
                  'liwc_anal.result.discrep',
                  'liwc_anal.result.tentat',
                  'liwc_anal.result.certain',
                  'liwc_anal.result.inhib',
                  'liwc_anal.result.incl',
                  'liwc_anal.result.excl',
                  'liwc_anal.result.percept',
                  'liwc_anal.result.see',
                  'liwc_anal.result.hear',
                  'liwc_anal.result.feel',
                  'liwc_anal.result.bio',
                  'liwc_anal.result.body',
                  'liwc_anal.result.health',
                  'liwc_anal.result.sexual',
                  'liwc_anal.result.ingest',
                  'liwc_anal.result.relativ',
                  'liwc_anal.result.motion',
                  'liwc_anal.result.space',
                  'liwc_anal.result.time',
                  'liwc_anal.result.work',
                  'liwc_anal.result.achieve',
                  'liwc_anal.result.leisure',
                  'liwc_anal.result.home',
                  'liwc_anal.result.money',
                  'liwc_anal.result.relig',
                  'liwc_anal.result.death',
                  'liwc_anal.result.assent',
                  'liwc_anal.result.nonfl',
                  'liwc_anal.result.filler',
                  'liwc_anal.result.Period',
                  'liwc_anal.result.Comma',
                  'liwc_anal.result.Colon',
                  'liwc_anal.result.SemiC',
                  'liwc_anal.result.QMark',
                  'liwc_anal.result.Exclam',
                  'liwc_anal.result.Dash',
                  'liwc_anal.result.Quote',
                  'liwc_anal.result.Apostro',
                  'liwc_anal.result.Parenth',
                  'liwc_anal.result.OtherP',
                  'liwc_anal.result.AllPct']
        writer = csv.DictWriter(outfile, fieldnames=fields)
        writer.writeheader()
        for x in cursor:
            writer.writerow(x)

def export_net_agg(dbname, colname, file_name):
    db = dbutil.db_connect_no_auth(dbname)
    poidb = db[colname]
    cursor = poidb.find({}, {'_id': 0, 'id0': 1, 'id1': 1, 'relationship': 1, 'count': 1})
    with open(file_name+'.csv', 'w') as outfile:
        fields = ['id0', 'id1', 'relationship', 'count']
        writer = csv.DictWriter(outfile, fieldnames=fields)
        writer.writeheader()
        for x in cursor:
            relat = x['relationship']
            if relat == 'reply-to' or relat == 'mentioned':
                writer.writerow(x)

def export_poi_echelon(dbname,colname, file_name):
    db = dbutil.db_connect_no_auth(dbname)
    poidb = db[colname]
    cursor = poidb.find({}, {'_id': 0,
                           'id':1,
                            'screen_name':1,
                            'datetime_joined_twitter':1,
                            'description':1,
                            'follower_auth_error_flag':1,
                            'timeline_auth_error_flag':1,
                            'lang':1,
                            'location':1,
                            'ds_gender':1,
                            'text_anal.gw.value':1,
                            'text_anal.cw.value':1,
                            'text_anal.edword_count.value':1,
                            'text_anal.h.value':1,
                            'text_anal.a.value':1,
                            'text_anal.lw.value':1,
                            'text_anal.hw.value':1,
                            'rliwc_anal.result.WC':1,
                            'rliwc_anal.result.WPS':1,
                            'rliwc_anal.result.Sixltr':1,
                            'rliwc_anal.result.Dic':1,
                            'rliwc_anal.result.Numerals':1,
                            'rliwc_anal.result.funct':1,
                            'rliwc_anal.result.pronoun':1,
                            'rliwc_anal.result.ppron':1,
                            'rliwc_anal.result.i':1,
                            'rliwc_anal.result.we':1,
                            'rliwc_anal.result.you':1,
                            'rliwc_anal.result.shehe':1,
                            'rliwc_anal.result.they':1,
                            'rliwc_anal.result.ipron':1,
                            'rliwc_anal.result.article':1,
                            'rliwc_anal.result.verb':1,
                            'rliwc_anal.result.auxverb':1,
                            'rliwc_anal.result.past':1,
                            'rliwc_anal.result.present':1,
                            'rliwc_anal.result.future':1,
                            'rliwc_anal.result.adverb':1,
                            'rliwc_anal.result.preps':1,
                            'rliwc_anal.result.conj':1,
                            'rliwc_anal.result.negate':1,
                            'rliwc_anal.result.quant':1,
                            'rliwc_anal.result.number':1,
                            'rliwc_anal.result.swear':1,
                            'rliwc_anal.result.social':1,
                            'rliwc_anal.result.family':1,
                            'rliwc_anal.result.friend':1,
                            'rliwc_anal.result.humans':1,
                            'rliwc_anal.result.affect':1,
                            'rliwc_anal.result.posemo':1,
                            'rliwc_anal.result.negemo':1,
                            'rliwc_anal.result.anx':1,
                            'rliwc_anal.result.anger':1,
                            'rliwc_anal.result.sad':1,
                            'rliwc_anal.result.cogmech':1,
                            'rliwc_anal.result.insight':1,
                            'rliwc_anal.result.cause':1,
                            'rliwc_anal.result.discrep':1,
                            'rliwc_anal.result.tentat':1,
                            'rliwc_anal.result.certain':1,
                            'rliwc_anal.result.inhib':1,
                            'rliwc_anal.result.incl':1,
                            'rliwc_anal.result.excl':1,
                            'rliwc_anal.result.percept':1,
                            'rliwc_anal.result.see':1,
                            'rliwc_anal.result.hear':1,
                            'rliwc_anal.result.feel':1,
                            'rliwc_anal.result.bio':1,
                            'rliwc_anal.result.body':1,
                            'rliwc_anal.result.health':1,
                            'rliwc_anal.result.sexual':1,
                            'rliwc_anal.result.ingest':1,
                            'rliwc_anal.result.relativ':1,
                            'rliwc_anal.result.motion':1,
                            'rliwc_anal.result.space':1,
                            'rliwc_anal.result.time':1,
                            'rliwc_anal.result.work':1,
                            'rliwc_anal.result.achieve':1,
                            'rliwc_anal.result.leisure':1,
                            'rliwc_anal.result.home':1,
                            'rliwc_anal.result.money':1,
                            'rliwc_anal.result.relig':1,
                            'rliwc_anal.result.death':1,
                            'rliwc_anal.result.assent':1,
                            'rliwc_anal.result.nonfl':1,
                            'rliwc_anal.result.filler':1,
                            'rliwc_anal.result.Period':1,
                            'rliwc_anal.result.Comma':1,
                            'rliwc_anal.result.Colon':1,
                            'rliwc_anal.result.SemiC':1,
                            'rliwc_anal.result.QMark':1,
                            'rliwc_anal.result.Exclam':1,
                            'rliwc_anal.result.Dash':1,
                            'rliwc_anal.result.Quote':1,
                            'rliwc_anal.result.Apostro':1,
                            'rliwc_anal.result.Parenth':1,
                            'rliwc_anal.result.OtherP':1,
                            'rliwc_anal.result.AllPct':1
                            })
    with open(file_name+'.csv', 'w') as outfile:
        fields = ['id',
                    'screen_name',
                    'datetime_joined_twitter',
                    'description',
                    'follower_auth_error_flag',
                    'timeline_auth_error_flag',
                    'lang',
                    'location',
                    'ds_gender',
                    'text_anal.gw.value',
                    'text_anal.cw.value',
                    'text_anal.edword_count.value',
                    'text_anal.h.value',
                    'text_anal.a.value',
                    'text_anal.lw.value',
                    'text_anal.hw.value',
                    'rliwc_anal.result.WC',
                    'rliwc_anal.result.WPS',
                    'rliwc_anal.result.Sixltr',
                    'rliwc_anal.result.Dic',
                    'rliwc_anal.result.Numerals',
                    'rliwc_anal.result.funct',
                    'rliwc_anal.result.pronoun',
                    'rliwc_anal.result.ppron',
                    'rliwc_anal.result.i',
                    'rliwc_anal.result.we',
                    'rliwc_anal.result.you',
                    'rliwc_anal.result.shehe',
                    'rliwc_anal.result.they',
                    'rliwc_anal.result.ipron',
                    'rliwc_anal.result.article',
                    'rliwc_anal.result.verb',
                    'rliwc_anal.result.auxverb',
                    'rliwc_anal.result.past',
                    'rliwc_anal.result.present',
                    'rliwc_anal.result.future',
                    'rliwc_anal.result.adverb',
                    'rliwc_anal.result.preps',
                    'rliwc_anal.result.conj',
                    'rliwc_anal.result.negate',
                    'rliwc_anal.result.quant',
                    'rliwc_anal.result.number',
                    'rliwc_anal.result.swear',
                    'rliwc_anal.result.social',
                    'rliwc_anal.result.family',
                    'rliwc_anal.result.friend',
                    'rliwc_anal.result.humans',
                    'rliwc_anal.result.affect',
                    'rliwc_anal.result.posemo',
                    'rliwc_anal.result.negemo',
                    'rliwc_anal.result.anx',
                    'rliwc_anal.result.anger',
                    'rliwc_anal.result.sad',
                    'rliwc_anal.result.cogmech',
                    'rliwc_anal.result.insight',
                    'rliwc_anal.result.cause',
                    'rliwc_anal.result.discrep',
                    'rliwc_anal.result.tentat',
                    'rliwc_anal.result.certain',
                    'rliwc_anal.result.inhib',
                    'rliwc_anal.result.incl',
                    'rliwc_anal.result.excl',
                    'rliwc_anal.result.percept',
                    'rliwc_anal.result.see',
                    'rliwc_anal.result.hear',
                    'rliwc_anal.result.feel',
                    'rliwc_anal.result.bio',
                    'rliwc_anal.result.body',
                    'rliwc_anal.result.health',
                    'rliwc_anal.result.sexual',
                    'rliwc_anal.result.ingest',
                    'rliwc_anal.result.relativ',
                    'rliwc_anal.result.motion',
                    'rliwc_anal.result.space',
                    'rliwc_anal.result.time',
                    'rliwc_anal.result.work',
                    'rliwc_anal.result.achieve',
                    'rliwc_anal.result.leisure',
                    'rliwc_anal.result.home',
                    'rliwc_anal.result.money',
                    'rliwc_anal.result.relig',
                    'rliwc_anal.result.death',
                    'rliwc_anal.result.assent',
                    'rliwc_anal.result.nonfl',
                    'rliwc_anal.result.filler',
                    'rliwc_anal.result.Period',
                    'rliwc_anal.result.Comma',
                    'rliwc_anal.result.Colon',
                    'rliwc_anal.result.SemiC',
                    'rliwc_anal.result.QMark',
                    'rliwc_anal.result.Exclam',
                    'rliwc_anal.result.Dash',
                    'rliwc_anal.result.Quote',
                    'rliwc_anal.result.Apostro',
                    'rliwc_anal.result.Parenth',
                    'rliwc_anal.result.OtherP',
                    'rliwc_anal.result.AllPct',
                    ]
        writer = csv.DictWriter(outfile, fieldnames=fields)
        writer.writeheader()
        for x in cursor:
            print x
            # writer.writerow(x)

# export_net_agg('echelon', 'mrredges_aggregated', 'reechelon_reply_mention')
export_poi_echelon('echelon', 'poi', 'echelon_poi')

# db = dbutil.db_connect_no_auth('echelon')
# poidb = db['poi']
# print poidb.find_one({},{'id':1,
#                             'screen_name':1,
#                             'datetime_joined_twitter':1,
#                             'description':1,
#                             'follower_auth_error_flag':1,
#                             'timeline_auth_error_flag':1,
#                             'lang':1,
#                             'location':1,
#                             'ds_gender':1,
#                             'text_anal.gw.value':1,
#                             'text_anal.cw.value':1})